# Generated by Django 2.2.10 on 2021-01-06 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=200, verbose_name='Вариант ответа')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название опроса')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание опроса')),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questiontext', models.CharField(max_length=300, verbose_name='Текст вопроса')),
                ('questiontype', models.CharField(choices=[('T', 'ответ текстом'), ('S', 'ответ с выбором одного варианта'), ('M', 'ответ с выбором нескольких вариантов')], max_length=3, verbose_name='Название опроса')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.Poll')),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textresponse', models.TextField(blank=True, null=True, verbose_name='Ответ в виде текста')),
                ('userid', models.PositiveIntegerField(default=0, verbose_name='Идентификатор пользователя')),
                ('answers', models.ManyToManyField(to='surveys.Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.Question')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.Question'),
        ),
    ]
